version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: npm run dev
    develop:
      watch:
        - path: ./app
          target: /app/app
          action: sync
        - path: ./package.json
          action: rebuild